---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: thoras-model-runner
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.cronJobModelCollector.schedule | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 900
      template:
        spec:
          serviceAccountName: thoras-collector
          restartPolicy: OnFailure
          containers:
          - image: {{ .Values.imageCredentials.registry }}/thoras-collector:{{ default .Values.thorasVersion .Values.cronJobModelCollector.image }}
            imagePullPolicy: Always
            name: metrics-collector
            command: ["/bin/sh", "-c"]
            args:
              - |
                node index.js runmodel \
                --modelImage={{ .Values.imageCredentials.registry }}/thoras-forecast:{{ default .Values.thorasVersion .Values.thorasForecast.image }} \
                --es=${ES_HOST}
            env:
              - name: THORAS_NS
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: ES_HOST
                valueFrom:
                  secretKeyRef:
                    name: thoras-elastic-password
                    key: host
            resources:
              limits:
                cpu: {{ .Values.cronJobModelCollector.limits.cpu }}
                memory: {{ .Values.cronJobModelCollector.limits.memory }}
              requests:
                cpu: {{ .Values.cronJobModelCollector.requests.cpu }}
                memory: {{ .Values.cronJobModelCollector.requests.memory }}
