---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "thoras.resourceLabels" (dict "root" . "component" .Values.thorasWorker.labels) | nindent 4 }}
  {{- with .Values.thorasWorker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.thorasWorker.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
{{- if .Values.imageCredentials.secretRef }}
  - name: {{ .Values.imageCredentials.secretRef }}
{{- else }}
  - name: thoras-secret-registry
{{- end }}
