{{- if .Values.featureFlags.thorasManageThoras.enabled }}
apiVersion: thoras.ai/v1
kind: AIScaleTarget
metadata:
  labels:
    {{- include "thoras.resourceLabels" (dict "root" . "component" .Values.metricsCollector.labels) | nindent 4 }}
  name: metrics-collector
  namespace: {{ .Release.Namespace }}
spec:
  horizontal:
    mode: recommendation
  model:
    forecast_blocks: {{ .Values.featureFlags.thorasManageThoras.db.forecastBlocks | default "4h0s" }}
    forecast_cron: {{ .Values.featureFlags.thorasManageThoras.db.forecastCron | default "17 * * * *" }}
    forecast_buffer_percentage: 33%
    mode: balanced
  scaleTargetRef:
    kind: Deployment
    name: metrics-collector
  vertical:
    containers:
    - cpu:
        lowerbound: 1m
      memory:
        lowerbound: 1Mi
        limit:
          ratio: 3
      name: 'blob-api'
    - cpu:
        lowerbound: 1m
      memory:
        lowerbound: 1Mi
      name: 'timescaledb'
    update_policy:
      update_mode: {{ .Values.featureFlags.thorasManageThoras.db.updateMode | default .Values.featureFlags.thorasManageThoras.updateMode | default "recreate" }}
    mode: {{ .Values.featureFlags.thorasManageThoras.mode | default "recommendation" }}
{{- end }}
