{{- if and .Values.metricsCollector.timescale.config.enabled (not (include "thoras.externalTimescaleEnabled" .)) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thoras-timescale-config
  namespace: {{ .Release.Namespace }}
data:{{ include "thoras.timescaleConfigData" . }}
{{- end }}
