---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: thoras-metrics-purge
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.metricsCollector.purge.schedule | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          serviceAccountName: thoras-collector
          restartPolicy: OnFailure
          containers:
          - image: {{ .Values.imageCredentials.registry }}/services:{{ default .Values.thorasVersion .Values.metricsCollector.collector.imageTag }}
            name: metrics-collector
            imagePullPolicy: "{{ .Values.imagePullPolicy }}"
            env:
              - name: "ELASTICSEARCH_URL"
                valueFrom:
                  secretKeyRef:
                    name: thoras-elastic-password
                    key: host
              - name: SLACK_WEBHOOK_URL
                valueFrom:
                  secretKeyRef:
                  {{- if and .Values.slackWebhookUrlSecretRefName .Values.slackWebhookUrlSecretRefKey }}
                    name: {{ .Values.slackWebhookUrlSecretRefName }}
                    key: {{ .Values.slackWebhookUrlSecretRefKey }}
                  {{- else }}
                    name: thoras-slack
                    key: webhookUrl
                  {{- end }}
              - name: SLACK_ERRORS_ENABLED
                value: "{{ .Values.metricsCollector.slackErrorsEnabled | default .Values.slackErrorsEnabled }}"
              - name: DATABASE_HOST
                valueFrom:
                  secretKeyRef:
                    name: thoras-timescale-password
                    key: host
              - name: SERVICE_POSTGRESQL_DSN
                value: "$(DATABASE_HOST)/thoras?sslmode=disable"
              - name: "SERVICE_LOG_LEVEL"
                value: {{ default .Values.logLevel .Values.metricsCollector.purge.logLevel }}
              - name: SERVICE_CLUSTER_NAME
                value: "{{ .Values.cluster.name }}"
            command: ["/bin/sh", "-c"]
            args:
              - |
                ./metrics-collector purge metrics \
                --metric-ttl={{ .Values.metricsCollector.purge.ttl }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}

