---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: thoras-metrics-purge
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.metricsCollector.purge.schedule | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          serviceAccountName: thoras-collector
          restartPolicy: OnFailure
          containers:
          - image: {{ .Values.imageCredentials.registry }}/thoras-collector:{{ default .Values.thorasVersion .Values.metricsCollector.collector.imageTag }}
            imagePullPolicy: Always
            name: metrics-collector
            env:
              - name: "ES_HOST"
                valueFrom:
                  secretKeyRef:
                    name: thoras-elastic-password
                    key: host
            command: ["/bin/sh", "-c"]
            args:
              - |
                node index.js \
                purge \
                --es=${ES_HOST} \
                --ttl={{ .Values.metricsCollector.purge.ttl }}
