---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: thoras-metrics-purge
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.metricsCollector.purge.schedule | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          serviceAccountName: thoras-collector
          restartPolicy: OnFailure
          containers:
          - image: {{ .Values.imageCredentials.registry }}/thoras-collector:{{ default .Values.thorasVersion .Values.metricsCollector.collector.imageTag }}
            name: metrics-collector
            imagePullPolicy: "{{ .Values.imagePullPolicy }}"
            env:
              - name: "ES_HOST"
                valueFrom:
                  secretKeyRef:
                    name: thoras-elastic-password
                    key: host
              - name: SLACK_WEBHOOK_URL
                valueFrom:
                  secretKeyRef:
                    name: thoras-slack
                    key: webhookUrl
              - name: SLACK_ERRORS_ENABLED
                value: {{ .Values.metricsCollector.slackErrorsEnabled | default .Values.slackErrorsEnabled }}
              - name: "LOGLEVEL"
                value: {{ default .Values.logLevel .Values.metricsCollector.purge.logLevel }}
            command: ["/bin/sh", "-c"]
            args:
              - |
                node index.js \
                purge \
                --es=${ES_HOST} \
                --ttl={{ .Values.metricsCollector.purge.ttl }}
