---
apiVersion: batch/v1
kind: Job
metadata:
  name: purge-forecast-cronjobs
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-delete
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      serviceAccountName: thoras-operator
      restartPolicy: OnFailure
      containers:
      - image: {{ .Values.imageCredentials.registry }}/services:{{ default .Values.thorasVersion .Values.metricsCollector.collector.imageTag }}
        name: metrics-collector
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        command: ["/bin/sh", "-c"]
        args:
          - |
            ./metrics-collector purge cronjobs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
