---
apiVersion: batch/v1
kind: Job
metadata:
  name: purge-forecast-cronjobs
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    helm.sh/hook: pre-delete
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      serviceAccountName: thoras-operator
      restartPolicy: OnFailure
      containers:
      - image: {{ .Values.imageCredentials.registry }}/services:{{ default .Values.thorasVersion .Values.metricsCollector.collector.imageTag }}
        name: metrics-collector
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        command: ["/bin/sh", "-c"]
        args:
          - |
            ./metrics-collector purge cronjobs