{{- if and (include "thoras.persistenceEnabled" .) (or (not .Values.featureFlags.enableNoBlobApiServer) (not (include "thoras.externalTimescaleEnabled" .)))}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-search-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thoras.resourceLabels" (dict "root" . "component" .Values.metricsCollector.labels) | nindent 4 }}
spec:
  {{- if .Values.metricsCollector.persistence.volumeName }}
  volumeName: {{ .Values.metricsCollector.persistence.volumeName }}
  {{- end }}
  {{- with .Values.metricsCollector.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    - {{ .Values.metricsCollector.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.metricsCollector.persistence.pvcStorageRequestSize | default "3Gi" }}
{{- end }}
