{{- define "thoras.collector.roles" }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if .rbacNamespace }}
kind: Role
metadata:
  name: {{ print "thoras-collector-" .rbacNamespace }}
  namespace: {{ .rbacNamespace }}
{{- else }}
kind: ClusterRole
metadata:
  name: thoras-collector
{{- end }}
  labels:
    {{- include "thoras.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - '*/scale'
  - '*/status'
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - verticalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - thoras.ai
  resources:
  - 'AIScaleTarget'
  - 'aiscaletargets/status'
  - 'aiscaletargets'
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - apps
  - argoproj.io
  resources:
  - '*'
  verbs:
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if .rbacNamespace }}
kind: RoleBinding
metadata:
  name: {{ print "thoras-collector-" .rbacNamespace }}
  namespace: {{ .rbacNamespace }}
{{- else }}
kind: ClusterRoleBinding
metadata:
  name: thoras-collector
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    {{- include "thoras.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
{{- if .rbacNamespace }}
  kind: Role
  name: {{ print "thoras-collector-" .rbacNamespace }}
{{- else }}
  kind: ClusterRole
  name: thoras-collector
{{- end }}
subjects:
- kind: ServiceAccount
  name: thoras-collector
  namespace: {{ .Release.Namespace }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "thoras.labels" . | nindent 4 }}
  name: thoras-collector
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
{{- if .Values.imageCredentials.secretRef }}
  - name: {{ .Values.imageCredentials.secretRef }}
{{- else }}
  - name: thoras-secret-registry
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "thoras.labels" . | nindent 4 }}
  name: thoras-collector-aggregated-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:aggregated-metrics-reader
subjects:
- kind: ServiceAccount
  name: thoras-collector
  namespace: {{ .Release.Namespace }}

{{- if .Values.rbac.namespaces}}
  {{- range $idx, $namespace := .Values.rbac.namespaces }}
    {{- template "thoras.collector.roles" ($ | deepCopy | merge (dict "rbacNamespace" $namespace) ) }}
  {{- end}}
{{- else }}
  {{- template "thoras.collector.roles" $ }}
{{- end }}
