---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "labels" . | nindent 4 }}
  name: thoras-collector
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
{{- if .Values.imageCredentials.secretRef }}
  - name: {{ .Values.imageCredentials.secretRef }}
{{- else }}
  - name: thoras-secret-registry
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "labels" . | nindent 4 }}
  name: thoras-collector-aggregated-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:aggregated-metrics-reader
subjects:
- kind: ServiceAccount
  name: thoras-collector
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "labels" . | nindent 4 }}
  name: thoras-collector-thoras-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: thoras-operator
subjects:
- kind: ServiceAccount
  name: thoras-collector
  namespace: {{ .Release.Namespace }}
