{{- $newEsPassword := randAlphaNum 16 }}
---
apiVersion: v1
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "thoras-elastic-password") }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $esPassword := (get $secretData "password") | default ((.Values.metricsCollector.search.elasticPassword | default $newEsPassword) | b64enc) }}
  password: {{ $esPassword | quote }}
  host: {{ (printf "http://elastic:%s@%s:%d" ($esPassword | b64dec) .Values.metricsCollector.search.name (.Values.metricsCollector.search.containerPort | int)) | b64enc | quote }}
kind: Secret
metadata:
  name: thoras-elastic-password
---
{{- $newPgPassword := randAlphaNum 16 }}
apiVersion: v1
kind: Secret
metadata:
  name: thoras-timescale-password
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "thoras-timescale-password") }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $pgPassword := (get $secretData "password") | default ((.Values.metricsCollector.timescale.password | default $newPgPassword) | b64enc) }}
  password: {{ $pgPassword | quote }}
  host: {{ (printf "postgres://postgres:%s@%s:%d?sslmode=disable" ($pgPassword | b64dec) .Values.metricsCollector.timescale.name (.Values.metricsCollector.timescale.containerPort | int)) | b64enc | quote }}
