{{- $newEsPassword := randAlphaNum 16 }}
---
apiVersion: v1
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "thoras-elastic-password") }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $esPassword := (get $secretData "password") | default ((.Values.metricsCollector.search.elasticPassword | default $newEsPassword) | b64enc) }}
  password: {{ $esPassword | quote }}
  host: {{ (printf "http://elastic:%s@%s:%d" ($esPassword | b64dec) .Values.metricsCollector.search.name (.Values.metricsCollector.search.containerPort | int)) | b64enc | quote }}
kind: Secret
metadata:
  name: thoras-elastic-password
