---
{{- $newPgPassword := randAlphaNum 16 }}
apiVersion: v1
kind: Secret
metadata:
  name: thoras-timescale-password
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "thoras-timescale-password") }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $pgPassword := (get $secretData "password") | default ((.Values.metricsCollector.timescale.password | default $newPgPassword) | b64enc) }}
  password: {{ $pgPassword | quote }}
  host: {{ (printf "postgres://postgres:%s@%s:%d" ($pgPassword | b64dec) .Values.metricsCollector.timescale.name (.Values.metricsCollector.timescale.containerPort | int)) | b64enc | quote }}
