{{- if and .Values.thorasLicenseKey (not (.Values.imageCredentials.existingSecret).secretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: thoras-secret-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thoras.resourceLabels" (dict "root" .) | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: Prune=false
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
