{{- if and .Values.serviceMonitor.enabled .Values.consoleApi.enabled .Values.consoleApi.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thoras-console-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thoras-console.resourceLabels" (dict "root" . "component" .Values.consoleApi.labels) | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: thoras-console-api
  endpoints:
    - port: http-metrics
      path: /metrics
      {{- with .Values.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
{{- end }}
