---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thoras-api-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thoras-api-server
  template:
    metadata:
      labels:
        app: thoras-api-server
        app.kubernetes.io/name: {{ .Chart.Name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- with .Values.thorasApiServer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: thoras-collector
      volumes:
        - name: tls
          secret:
            secretName: thoras-api-server-cert
      containers:
      - image: {{ .Values.imageCredentials.registry }}/thoras-external-metrics-server:{{ default .Values.thorasVersion .Values.thorasApiServer.imageTag }}
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        name: thoras-api-server
        env:
          - name: "ES_HOST"
            valueFrom:
              secretKeyRef:
                name: thoras-elastic-password
                key: host
          - name: SLACK_WEBHOOK_URL
            valueFrom:
              secretKeyRef:
                name: thoras-slack
                key: webhookUrl
          - name: SLACK_ERRORS_ENABLED
            value: "{{ .Values.thorasApiServer.slackErrorsEnabled | default .Values.slackErrorsEnabled }}"
          - name: "LOGLEVEL"
            value: {{ default .Values.logLevel .Values.thorasApiServer.logLevel }}
        volumeMounts:
          - name: tls
            mountPath: /apps/packages/thoras-external-metrics-server/cert.pem
            subPath: tls.crt
            readOnly: true
          - name: tls
            mountPath: /apps/packages/thoras-external-metrics-server/key.pem
            subPath: tls.key
            readOnly: true
        ports:
        - containerPort: {{ .Values.thorasApiServer.containerPort }}
        resources:
          limits:
            memory: {{ .Values.thorasApiServer.limits.memory }}
          requests:
            cpu: {{ .Values.thorasApiServer.requests.cpu }}
            memory: {{ .Values.thorasApiServer.requests.memory }}
