---
apiVersion: v1
kind: Service
metadata:
  name: thoras-api-server
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.thorasApiServer.port }}
    protocol: TCP
    targetPort: {{ .Values.thorasApiServer.containerPort }}
  selector:
    app: thoras-api-server
