{{- $ca := genCA "thoras-api-server-v2-ca" 3650 }}
{{- $cn := "thoras-api-server-v2" }}
{{- $dns1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $dns2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list "thoras-api-server-v2" $dns1 $dns2) 3650 $ca }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: thoras-api-server-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "thoras-api-server-cert") }}
  {{- $secretData := (get $secretObj "data") | default dict }}

  {{- $secretCert := (get $secretData "tls.crt") | default (printf "%s\n%s" $cert.Cert $ca.Cert | b64enc) }}
  {{- $secretKey := (get $secretData "tls.key") | default ($cert.Key | b64enc) }}
  {{- $secretCaCert := (get $secretData "ca.crt") | default ($ca.Cert | b64enc) }}
  tls.crt: {{ $secretCert | quote }}
  tls.key: {{ $secretKey | quote }}
  ca.crt: {{ $secretCaCert | quote }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "pods.thoras.ai"
webhooks:
- name: "pods.thoras.ai"
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: thoras-api-server-v2
      path: /mutate
    caBundle: {{ $secretCaCert | quote }}
  sideEffects: None
  failurePolicy: 'Ignore'
  admissionReviewVersions:
    - v1
- name: "scale.thoras.ai"
  rules:
  - apiGroups:   ["*"]
    apiVersions: ["*"]
    operations:  ["UPDATE"]
    resources:   ["deployments/scale"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: thoras-api-server-v2
      path: /mutate
    caBundle: {{ $secretCaCert | quote }}
  sideEffects: None
  failurePolicy: 'Ignore'
  admissionReviewVersions:
    - v1
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "validation.thoras.ai"
webhooks:
  - name: "ast-validation.thoras.ai"
    rules:
    - apiGroups:   ["thoras.ai"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["aiscaletargets"]
      scope:       "Namespaced"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: thoras-api-server-v2
        path: /validate
      caBundle: {{ $secretCaCert | quote }}
    sideEffects: None
    failurePolicy: 'Ignore'
    timeoutSeconds: 5
    admissionReviewVersions:
      - v1