{{- define "thoras.api.server.v2.roles" }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if .rbacNamespace }}
kind: Role
metadata:
  namespace: {{ .rbacNamespace }}
{{- else }}
kind: ClusterRole
metadata:
{{- end }}
  labels:
    {{- include "thoras.labels" . | nindent 4 }}
  name: {{ .Values.thorasApiServerV2.serviceAccount.name }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - apps
  - argoproj.io
  resources:
  - '*'
  verbs:
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if .rbacNamespace }}
kind: RoleBinding
metadata:
  namespace: {{ .rbacNamespace }}
{{- else }}
kind: ClusterRoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    {{- include "thoras.labels" . | nindent 4 }}
  name: {{ .Values.thorasApiServerV2.serviceAccount.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
{{- if .rbacNamespace }}
  kind: Role
{{- else }}
  kind: ClusterRole
{{- end }}
  name: {{ .Values.thorasApiServerV2.serviceAccount.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.thorasApiServerV2.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}

{{- if and .Values.thorasApiServerV2.rbac.create  }}
  {{- if .Values.rbac.namespaces}}
    {{- range $idx, $namespace := .Values.rbac.namespaces }}
      {{- template "thoras.api.server.v2.roles" ($ | deepCopy | merge (dict "rbacNamespace" $namespace) ) }}
    {{- end}}
  {{- else }}
    {{- template "thoras.api.server.v2.roles" $ }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ print .Values.thorasApiServerV2.serviceAccount.name "-thoras" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thoras.labels" . | nindent 4 }}
rules:
- apiGroups:
  - thoras.ai
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - 'namespaces'
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ print .Values.thorasApiServerV2.serviceAccount.name "-thoras" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thoras.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ print .Values.thorasApiServerV2.serviceAccount.name "-thoras" }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.thorasApiServerV2.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ print .Values.thorasApiServerV2.serviceAccount.name "-thoras" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thoras.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ print .Values.thorasApiServerV2.serviceAccount.name "-thoras" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thoras.labels" . | nindent 4 }}
roleRef:
  kind: Role
  name: {{ print .Values.thorasApiServerV2.serviceAccount.name "-thoras" }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.thorasApiServerV2.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
