{{ if $.Values.thorasReasoning.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thoras-reasoning-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.thorasReasoning.api.replicas }}
  selector:
    matchLabels:
      app: thoras-reasoning-api
  template:
    metadata:
      labels:
        app: thoras-reasoning-api
        app.kubernetes.io/name: {{ .Chart.Name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.thorasAgent.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.thorasReasoning.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: thoras-collector
      containers:
      - image: {{ .Values.imageCredentials.registry }}/thoras-forecast:{{ default .Values.thorasVersion .Values.thorasReasoning.api.imageTag }}
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        name: thoras-reasoning-api
        command:
          - "gunicorn"
          - "--workers"
          - "4"
          - "-k"
          - "gevent"
          - "--bind"
          - "0.0.0.0:8080"
          - "forecast.api.routes:app"
        env:
          - name: "ELASTICSEARCH_URL"
            valueFrom:
              secretKeyRef:
                name: thoras-elastic-password
                key: host
          - name: SLACK_WEBHOOK_URL
            valueFrom:
              secretKeyRef:
            {{- if and .Values.slackWebhookUrlSecretRefName .Values.slackWebhookUrlSecretRefKey }}
                name: {{ .Values.slackWebhookUrlSecretRefName }}
                key: {{ .Values.slackWebhookUrlSecretRefKey }}
            {{- else }}
                name: thoras-slack
                key: webhookUrl
            {{- end }}
          - name: SLACK_ERRORS_ENABLED
            value: "{{ .Values.thorasReasoning.api.slackErrorsEnabled | default .Values.slackErrorsEnabled }}"
          - name: "LOGLEVEL"
            value: {{ default .Values.logLevel .Values.thorasReasoning.api.logLevel }}
          - name: "PROMETHEUS_BASE_URL"
            value: {{ .Values.thorasReasoning.connectors.prometheus.baseUrl }}
          - name: API_BASE_URL
            value: "http://thoras-api-server-v2"
        ports:
        - containerPort: {{ .Values.thorasReasoning.api.containerPort }}
        resources:
          limits:
            memory: {{ .Values.thorasReasoning.api.limits.memory }}
          requests:
            cpu: {{ .Values.thorasReasoning.api.requests.cpu }}
            memory: {{ .Values.thorasReasoning.api.requests.memory }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
