{{- if $.Values.thorasReasoning.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "thoras.labels" . | nindent 4 }}
  name: {{ .Values.thorasReasoning.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
{{- if .Values.imageCredentials.secretRef }}
  - name: {{ .Values.imageCredentials.secretRef }}
{{- else }}
  - name: thoras-secret-registry
{{- end }}

{{- end}}
