{{ if $.Values.thorasReasoning.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: thoras-reasoning-api
  namespace: {{ .Release.Namespace }}
  {{- with .Values.thorasReasoning.api.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: {{ .Values.thorasReasoning.api.port }}
    protocol: TCP
    targetPort: {{ .Values.thorasReasoning.api.containerPort }}
  selector:
    app: thoras-reasoning-api
{{ end }}
