---
apiVersion: v1
kind: Service
metadata:
  name: thoras-console-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: thoras-console-frontend
    {{- include "thoras-console.resourceLabels" (dict "root" . "component" .Values.consoleFrontend.labels) | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.consoleFrontend.port }}
    protocol: TCP
    targetPort: {{ .Values.consoleFrontend.containerPort }}
  selector:
    app: thoras-console-frontend
