---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aiscaletargets.thoras.ai
spec:
  names:
    kind: AIScaleTarget
    listKind: AIScaleTargetList
    plural: aiscaletargets
    shortNames:
      - ast
  group: thoras.ai
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - scaleTargetRef
                - model
              properties:
                scaleTargetRef:
                  type: object
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      default: ""
                      type: string
                    name:
                      default: ""
                      type: string
                  required:
                      - kind
                      - name
                horizontal:
                  type: object
                  description: HorizontalPodAutoscalerSpec describes the desired functionality of the HorizontalPodAutoscaler.
                  required:
                    - mode
                    - maxReplicas
                    - replicas
                  properties:
                    mode:
                      type: string
                    metrics:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                            pattern: '^(Object|Resource|Pods)$'
                          object:
                            type: object
                            required:
                              - metric
                              - describedObject
                              - target
                            properties:
                              metric:
                                type: object
                                required:
                                  - name
                                properties:
                                  name:
                                    type: string
                                  selector:
                                    type: string
                              describedObject:
                                type: object
                                required:
                                  - kind
                                  - name
                                properties:
                                  apiVersion:
                                    type: string
                                  kind:
                                    type: string
                                  name:
                                    type: string
                              target:
                                type: object
                                required:
                                  - type
                                properties:
                                  type:
                                    type: string
                                    pattern: '^(Utilization|Value|AverageValue)$'
                                  averageUtilization:
                                    anyOf:
                                      - type: integer
                                      - type: string
                                    x-kubernetes-int-or-string: true
                                  averageValue:
                                    anyOf:
                                      - type: integer
                                      - type: string
                                    x-kubernetes-int-or-string: true
                                  value:
                                    anyOf:
                                      - type: integer
                                      - type: string
                                    x-kubernetes-int-or-string: true
                          pods:
                            type: object
                            required:
                              - metric
                              - describedObject
                              - target
                            properties:
                              metric:
                                type: object
                                required:
                                  - name
                                properties:
                                  name:
                                    type: string
                                  selector:
                                    type: string
                              describedObject:
                                type: object
                                required:
                                  - kind
                                  - name
                                properties:
                                  apiVersion:
                                    type: string
                                  kind:
                                    type: string
                                  name:
                                    type: string
                                  namespace:
                                    type: string
                              target:
                                type: object
                                required:
                                  - type
                                properties:
                                  type:
                                    type: string
                                    pattern: '^(Utilization|Value|AverageValue)$'
                                  averageUtilization:
                                    anyOf:
                                      - type: integer
                                      - type: string
                                    x-kubernetes-int-or-string: true
                                  averageValue:
                                    anyOf:
                                      - type: integer
                                      - type: string
                                    x-kubernetes-int-or-string: true
                                  value:
                                    anyOf:
                                      - type: integer
                                      - type: string
                                    x-kubernetes-int-or-string: true
                          resource:
                            type: object
                            properties:
                              name:
                                type: string
                              target:
                                type: object
                                required:
                                  - type
                                properties:
                                  type:
                                    type: string
                                  averageUtilization:
                                    anyOf:
                                    - type: integer
                                    - type: string
                                    x-kubernetes-int-or-string: true
                                  averageValue:
                                    anyOf:
                                    - type: integer
                                    - type: string
                                    x-kubernetes-int-or-string: true
                    maxReplicas:
                      default: 0
                      format: int32
                      type: integer
                    minReplicas:
                      default: 0
                      format: int32
                      type: integer
                    replicas:
                      default: 1
                      format: int32
                      type: integer
                vertical:
                  type: object
                  required:
                    - mode
                  properties:
                    mode:
                      type: string
                    cpu:
                      type: object
                      properties:
                        lowerbound:
                            anyOf:
                              - type: integer
                              - type: string
                            x-kubernetes-int-or-string: true
                        upperbound:
                          anyOf:
                            - type: integer
                            - type: string
                          x-kubernetes-int-or-string: true
                    memory:
                      type: object
                      properties:
                        lowerbound:
                          anyOf:
                            - type: integer
                            - type: string
                          x-kubernetes-int-or-string: true
                        upperbound:
                          anyOf:
                            - type: integer
                            - type: string
                          x-kubernetes-int-or-string: true
                model:
                  type: object
                  required:
                    - mode
                  properties:
                    mode:
                      type: string
                    forecast_cron:
                      type: string
                      pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
                      default: '*/15 * * * *'
                    forecast_blocks:
                      anyOf:
                        - type: integer
                        - type: string
                      x-kubernetes-int-or-string: true
            status:
              type: object
              properties:
                replicas:
                  type: integer
                labelSelector:
                  type: string
                thorasSuggestedReplicas:
                  type: integer
      subresources:
        status: {}
        scale:
          specReplicasPath: .spec.horizontal.replicas
          statusReplicasPath: .status.replicas
          labelSelectorPath: .status.labelSelector
      additionalPrinterColumns:
        - jsonPath: .spec.model.mode
          name: Model
          type: string
        - jsonPath: .spec.horizontal.mode
          name: Horizontal
          type: string
        - jsonPath: .spec.vertical.mode
          name: Vertical
          type: string
        - jsonPath: .status.replicas
          name: Replicas
          type: number
