---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: matchlabels.thoras.ai
  labels:
    {{- include "thoras.labels" . | nindent 4 }}
spec:
  names:
    kind: MatchLabels
    listKind: MatchLabelsList
    plural: matchlabels
  group: thoras.ai
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - kind
              properties:
                kind:
                  type: string
                  description: Persistent entity in the system. Pod, ReplicationController, Service, Namespace, Node
                labels:
                  type: object
                  description: Free form key value pairs
                  additionalProperties:
                    type: string
