{{- if .Values.featureFlags.thorasManageThoras.enabled }}
apiVersion: thoras.ai/v1
kind: AIScaleTarget
metadata:
  labels:
    {{- include "thoras.resourceLabels" (dict "root" . "component" .Values.thorasOperator.labels) | nindent 4 }}
  name: thoras-operator
  namespace: {{ .Release.Namespace }}
spec:
  horizontal:
    mode: recommendation
  model:
    forecast_blocks: 20m
    forecast_interval: '15m'
    mode: balanced
  scaleTargetRef:
    kind: Deployment
    name: thoras-operator
  vertical:
    containers:
    - cpu:
        lowerbound: 1m
      memory:
        lowerbound: 1Mi
        limit:
          ratio: 3
      name: '*'
    update_policy:
      update_mode: {{ .Values.featureFlags.thorasManageThoras.updateMode | default "recreate" }}
    mode: {{ .Values.featureFlags.thorasManageThoras.mode | default "recommendation" }}
{{- end }}
