---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "thoras-console.resourceLabels" (dict "root" . "component" .Values.consoleApi.labels) | nindent 4 }}
  name: {{ .Values.consoleApi.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
{{- if .Values.imageCredentials.secretRef }}
  - name: {{ .Values.imageCredentials.secretRef }}
{{- else }}
  - name: thoras-console-secret-registry
{{- end }}
