{{- if .Values.thorasMonitorV2.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thoras-monitor-v2
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thoras-monitor-v2
  template:
    metadata:
      labels:
        app: thoras-monitor-v2
        app.kubernetes.io/name: {{ .Chart.Name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: thoras-monitor-v2
      containers:
      - name: thoras-monitor-v2
        image: {{ .Values.imageCredentials.registry }}/services:{{ default .Values.thorasVersion .Values.thorasMonitorV2.imageTag }}
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        command: ["/app/monitor"]
        env:
          - name: SERVICE_LOG_LEVEL
            value: {{ .Values.thorasMonitorV2.logLevel | default .Values.thorasMonitor.logLevel | default .Values.logLevel | quote }}
          - name: SERVICE_SLACK_WEBHOOK_URL
            valueFrom:
              secretKeyRef:
            {{- if and .Values.slackWebhookUrlSecretRefName .Values.slackWebhookUrlSecretRefKey }}
                name: {{ .Values.slackWebhookUrlSecretRefName }}
                key: {{ .Values.slackWebhookUrlSecretRefKey }}
            {{- else }}
                name: thoras-slack
                key: webhookUrl
            {{- end }}
          - name: SERVICE_SLACK_ERRORS_ENABLED
            value: "{{ .Values.thorasMonitorV2.slackErrorsEnabled | default .Values.thorasMonitor.slackErrorsEnabled | default .Values.slackErrorsEnabled }}"
          - name: SERVICE_CLUSTER_NAME
            value: "{{ .Values.cluster.name }}"
          - name: SERVICE_THORAS_API_BASE_URL
            value: "http://thoras-api-server-v2"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
